export const REQUEST_CURRENCIES = 'REQUEST_CURRENCIES';
export const RECEIVE_CURRENCIES_SUCCESS = 'RECEIVE_CURRENCIES_SUCCESS';
export const RECEIVE_CURRENCIES_FAILURE = 'RECEIVE_CURRENCIES_FAILURE';
export const REQUEST_EXPENSES = 'REQUEST_EXPENSES';
export const RECEIVE_EXPENSES_SUCCESS = 'RECEIVE_EXPENSES_SUCCESS';
export const RECEIVE_EXPENSES_FAILURE = 'RECEIVE_EXPENSES_FAILURE';
